spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://www.xdblog.site:3308/feed_demo0
        username: root
        password: 1234567
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://www.xdblog.site:3308/feed_demo1
        username: root
        password: 1234567
    rules:
      sharding:
        tables:
          feed_info:
            actual-data-nodes: ds0.feed_info_$->{0..1}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: feedinfo-table-inline
            key-generate-strategy:
              #自增列名称，缺省表示不使用自增主键生成器
              column: id
              #自增列值生成器类型，可使用用户自定义的列值生成器或选择内置类型：SNOWFLAKE/UUID
              key-generator-name: feedinfo-auincrkey
        sharding-algorithms:
          feedinfo-table-inline:
            type: INLINE
            props:
              algorithm-expression: feed_info_$->{user_id % 2}
        key-generators:
          feedinfo-auincrkey:
            type: snowflake

